### ISSUE TITLE
Can't load JSON from bytes python3.5

### ISSUE THREAD

**Issue by mateimicu** [user-cont/conu#251]
Conu version `conu==0.4.0`
Docker version
```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
Running this example
```python
#!/usr/bin/env python3
from conu import DockerBackend

backend = DockerBackend()
image = backend.ImageClass('docker.io/library/nginx')
container = image.run_via_binary()
```
I get this traceback:
```
16:46:28.671 backend.py        INFO   conu has initiated, welcome to the party!
16:46:28.685 __init__.py       INFO   docker environment info: 'Client:\n Version:      17.05.0-ce\n API version:  1.29\n Go version:   go1.7.5\n Git commit:   89658be\n Built:        Thu May  4 22:10:54 2017\n OS/Arch:      linux/amd64\n\nServer:\n Version:      17.05.0-ce\n API version:  1.29 (minimum version 1.12)\n Go version:   go1.7.5\n Git commit:   89658be\n Built:        Thu May  4 22:10:54 2017\n OS/Arch:      linux/amd64\n Experimental: false\n'
Traceback (most recent call last):
  File "./01_run_container.py", line 9, in <module>
    image = backend.ImageClass('docker.io/library/nginx')
  File "/home/<user>/.local/lib/python3.5/site-packages/conu/backend/docker/image.py", line 136, in __init__
    self.pull()
  File "/home/<user>/.local/lib/python3.5/site-packages/conu/backend/docker/image.py", line 185, in pull
    json_e = json.loads(json_s)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

I found the problem to be here https://github.com/user-cont/conu/blob/master/conu/backend/docker/image.py#L190
It seems that ` json_s` is of type `bytes`, I can fix this is the code with `json_s = json_s.decode()` but I was wondering if this is a problem only on my installation or if it's a bigger problem that needs to be investigated. 

EDIT:
If I print the `json_s` it looks like this ` b'{"status":"Pulling from library/nginx","id":"latest"}\r\n'`

**Comment by jpopelka** [comment]
[json.loads](https://docs.python.org/3/library/json.html#json.loads) in python < 3.6 does not accept bytes so this is issue on our side
