### ISSUE TITLE
enum strikes back

### ISSUE THREAD

**Issue by TomasTomecek** [user-cont/conu#314]
When I install conu from PyPI, this is what happens:
```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 6, in <module>
        import distutils.core
      File "/usr/lib64/python3.7/distutils/core.py", line 16, in <module>
        from distutils.dist import Distribution
      File "/usr/lib64/python3.7/distutils/dist.py", line 9, in <module>
        import re
      File "/usr/lib64/python3.7/re.py", line 143, in <module>
        class RegexFlag(enum.IntFlag):
    AttributeError: module 'enum' has no attribute 'IntFlag'
```

Do we just create a new upstream release?

**Comment by jpopelka** [comment]
> Do we just create a new upstream release?

I don't understand the question.

**Comment by TomasTomecek** [comment]
My point is that latest release of conu is unusable from Fedora and PyPI. We should do a new release ASAP.
